-- Tables owned by this app (the catalog tables are loaded from TMDB elsewhere).
-- Safe to re-run: `npm run db:schema`.

create table if not exists profiles (
  id integer generated by default as identity primary key,
  name text not null unique,
  is_guest boolean not null default false,
  color text not null,
  created_at timestamptz not null default now()
);

-- Databases created before profile colors existed.
alter table profiles add column if not exists color text;
update profiles set color = case when is_guest then '#2563eb' else '#dc2626' end
where color is null;
alter table profiles alter column color set not null;

create unique index if not exists profiles_name_lower_key on profiles (lower(name));

-- insert ... select (not on conflict) so re-runs don't burn identity values.
insert into profiles (name, is_guest, color)
select v.name, v.is_guest, v.color
from (values ('Manuel', false, '#dc2626'), ('Guest', true, '#2563eb')) as v (name, is_guest, color)
where not exists (select 1 from profiles p where lower(p.name) = lower(v.name));

create table if not exists profile_favorites (
  profile_id integer not null references profiles (id) on delete cascade,
  title_id bigint not null references titles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, title_id)
);

-- Small (256px) images, already cropped by the client.
create table if not exists profile_avatars (
  profile_id integer primary key references profiles (id) on delete cascade,
  content_type text not null,
  data bytea not null,
  updated_at timestamptz not null default now()
);

-- Write grants also cover the table lock taken while creating/deleting profiles.
grant select, insert, update, delete on profiles to app_api;
grant select, insert, delete on profile_favorites to app_api;
grant select, insert, update, delete on profile_avatars to app_api;
